export type InstructionPlatform = "windows" | "macos";
export type TypingLanguage =
  | "korean"
  | "japanese"
  | "french"
  | "spanish"
  | "german"
  | "portuguese"
  | "russian";
export type TypingDrillMode = "physical" | "committed";

export type TypingTrack = {
  language: TypingLanguage;
  selectionLabel: string;
};

export type TypingKeyLegend = {
  shifted?: string;
  base?: string;
};

export type TypingLesson = {
  id: string;
  language: TypingLanguage;
  languageTag: string;
  title: string;
  mode: TypingDrillMode;
  target: string;
  expectedText: string;
  sharedPhysicalCodes: string[];
  platformPhysicalCodes: Record<InstructionPlatform, string[]>;
  hint: string;
  keyLegends: Record<string, TypingKeyLegend>;
  instructions: Record<InstructionPlatform, string>;
};

export const instructionPlatformPreferenceKey = "meiki-typing-platform";

export const typingTracks: TypingTrack[] = [
  { language: "korean", selectionLabel: "Korean — 2-set Hangul" },
  { language: "japanese", selectionLabel: "Japanese — Romaji input" },
  { language: "french", selectionLabel: "French — Dead-key accents" },
  { language: "spanish", selectionLabel: "Spanish — Dead-key accents" },
  { language: "german", selectionLabel: "German — Umlauts and ß" },
  { language: "portuguese", selectionLabel: "Portuguese — Dead-key accents" },
  { language: "russian", selectionLabel: "Russian — ЙЦУКЕН" },
];

export const koreanKeyLegends: Record<string, TypingKeyLegend> = {
  KeyQ: { shifted: "ㅃ", base: "ㅂ" },
  KeyW: { shifted: "ㅉ", base: "ㅈ" },
  KeyE: { shifted: "ㄸ", base: "ㄷ" },
  KeyR: { shifted: "ㄲ", base: "ㄱ" },
  KeyT: { shifted: "ㅆ", base: "ㅅ" },
  KeyY: { base: "ㅛ" },
  KeyU: { base: "ㅕ" },
  KeyI: { base: "ㅑ" },
  KeyO: { shifted: "ㅒ", base: "ㅐ" },
  KeyP: { shifted: "ㅖ", base: "ㅔ" },
  KeyA: { base: "ㅁ" },
  KeyS: { base: "ㄴ" },
  KeyD: { base: "ㅇ" },
  KeyF: { base: "ㄹ" },
  KeyG: { base: "ㅎ" },
  KeyH: { base: "ㅗ" },
  KeyJ: { base: "ㅓ" },
  KeyK: { base: "ㅏ" },
  KeyL: { base: "ㅣ" },
  KeyZ: { base: "ㅋ" },
  KeyX: { base: "ㅌ" },
  KeyC: { base: "ㅊ" },
  KeyV: { base: "ㅍ" },
  KeyB: { base: "ㅠ" },
  KeyN: { base: "ㅜ" },
  KeyM: { base: "ㅡ" },
};

const russianKeyLegends: Record<string, TypingKeyLegend> = {
  Backquote: { shifted: "Ё", base: "ё" },
  KeyQ: { shifted: "Й", base: "й" },
  KeyW: { shifted: "Ц", base: "ц" },
  KeyE: { shifted: "У", base: "у" },
  KeyR: { shifted: "К", base: "к" },
  KeyT: { shifted: "Е", base: "е" },
  KeyY: { shifted: "Н", base: "н" },
  KeyU: { shifted: "Г", base: "г" },
  KeyI: { shifted: "Ш", base: "ш" },
  KeyO: { shifted: "Щ", base: "щ" },
  KeyP: { shifted: "З", base: "з" },
  BracketLeft: { shifted: "Х", base: "х" },
  BracketRight: { shifted: "Ъ", base: "ъ" },
  KeyA: { shifted: "Ф", base: "ф" },
  KeyS: { shifted: "Ы", base: "ы" },
  KeyD: { shifted: "В", base: "в" },
  KeyF: { shifted: "А", base: "а" },
  KeyG: { shifted: "П", base: "п" },
  KeyH: { shifted: "Р", base: "р" },
  KeyJ: { shifted: "О", base: "о" },
  KeyK: { shifted: "Л", base: "л" },
  KeyL: { shifted: "Д", base: "д" },
  Semicolon: { shifted: "Ж", base: "ж" },
  Quote: { shifted: "Э", base: "э" },
  KeyZ: { shifted: "Я", base: "я" },
  KeyX: { shifted: "Ч", base: "ч" },
  KeyC: { shifted: "С", base: "с" },
  KeyV: { shifted: "М", base: "м" },
  KeyB: { shifted: "И", base: "и" },
  KeyN: { shifted: "Т", base: "т" },
  KeyM: { shifted: "Ь", base: "ь" },
  Comma: { shifted: "Б", base: "б" },
  Period: { shifted: "Ю", base: "ю" },
  Slash: { shifted: ",", base: "." },
};

const koreanInstructions: Record<InstructionPlatform, string> = {
  windows:
    "Use 2-set Korean. On standard US hardware, use Right Alt for 한/영 switching.",
  macos:
    "Enable Korean input. On standard US hardware, use Right Command for switching.",
};

const japaneseInstructions: Record<InstructionPlatform, string> = {
  windows: "Use Microsoft Japanese IME with English 101/102-key hardware.",
  macos:
    "Use romaji input and enable “Use Caps Lock to switch to and from ABC.”",
};

const deadKeyInstructions: Record<InstructionPlatform, string> = {
  windows: "Use United States-International on Windows.",
  macos: "Use the standard U.S. layout on macOS.",
};

const russianInstructions: Record<InstructionPlatform, string> = {
  windows:
    "Add Russian on Windows and use the standard Russian keyboard layout.",
  macos:
    "Add a Russian input source on macOS that uses the displayed standard ЙЦУКЕН letter positions.",
};

export const typingLessons: TypingLesson[] = [
  {
    id: "typing-korean-basic-consonants",
    language: "korean",
    languageTag: "ko",
    title: "Basic consonants",
    mode: "physical",
    target: "ㅂ ㅈ ㄷ ㄱ ㅅ ㅁ ㄴ ㅇ ㄹ ㅎ ㅋ ㅌ ㅊ ㅍ",
    expectedText: "ㅂㅈㄷㄱㅅㅁㄴㅇㄹㅎㅋㅌㅊㅍ",
    sharedPhysicalCodes: [
      "KeyQ",
      "KeyW",
      "KeyE",
      "KeyR",
      "KeyT",
      "KeyA",
      "KeyS",
      "KeyD",
      "KeyF",
      "KeyG",
      "KeyZ",
      "KeyX",
      "KeyC",
      "KeyV",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "Press the consonant positions from the top row through the bottom row. No active Korean input source is required.",
    keyLegends: koreanKeyLegends,
    instructions: koreanInstructions,
  },
  {
    id: "typing-korean-basic-vowels",
    language: "korean",
    languageTag: "ko",
    title: "Basic vowels",
    mode: "physical",
    target: "ㅛ ㅕ ㅑ ㅐ ㅔ ㅗ ㅓ ㅏ ㅣ ㅠ ㅜ ㅡ",
    expectedText: "ㅛㅕㅑㅐㅔㅗㅓㅏㅣㅠㅜㅡ",
    sharedPhysicalCodes: [
      "KeyY",
      "KeyU",
      "KeyI",
      "KeyO",
      "KeyP",
      "KeyH",
      "KeyJ",
      "KeyK",
      "KeyL",
      "KeyB",
      "KeyN",
      "KeyM",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "Press each base vowel position in row order. The physical drill is independent of the active input source.",
    keyLegends: koreanKeyLegends,
    instructions: koreanInstructions,
  },
  {
    id: "typing-korean-shift-forms",
    language: "korean",
    languageTag: "ko",
    title: "Shift forms",
    mode: "physical",
    target: "ㅃ ㅉ ㄸ ㄲ ㅆ ㅒ ㅖ",
    expectedText: "ㅃㅉㄸㄲㅆㅒㅖ",
    sharedPhysicalCodes: [
      "ShiftLeft",
      "KeyQ",
      "KeyW",
      "KeyE",
      "KeyR",
      "KeyT",
      "KeyO",
      "KeyP",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "Hold Shift, then press Q, W, E, R, T, O, and P. Release Shift after the final key.",
    keyLegends: koreanKeyLegends,
    instructions: koreanInstructions,
  },
  {
    id: "typing-korean-compound-vowels",
    language: "korean",
    languageTag: "ko",
    title: "Compound vowels",
    mode: "physical",
    target: "ㅘ ㅚ ㅝ ㅢ",
    expectedText: "ㅘㅚㅝㅢ",
    sharedPhysicalCodes: [
      "KeyH",
      "KeyK",
      "KeyH",
      "KeyL",
      "KeyN",
      "KeyJ",
      "KeyM",
      "KeyL",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "Combine H K for ㅘ, H L for ㅚ, N J for ㅝ, and M L for ㅢ.",
    keyLegends: koreanKeyLegends,
    instructions: koreanInstructions,
  },
  {
    id: "typing-korean-syllable-blocks",
    language: "korean",
    languageTag: "ko",
    title: "Syllable-block assembly",
    mode: "committed",
    target: "한",
    expectedText: "한",
    sharedPhysicalCodes: ["KeyG", "KeyK", "KeyS"],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "With 2-set Korean active, type G K S and commit the complete syllable block 한.",
    keyLegends: koreanKeyLegends,
    instructions: koreanInstructions,
  },
  {
    id: "typing-korean-short-words",
    language: "korean",
    languageTag: "ko",
    title: "Short words",
    mode: "committed",
    target: "안녕",
    expectedText: "안녕",
    sharedPhysicalCodes: ["KeyD", "KeyK", "KeyS", "KeyS", "KeyU", "KeyD"],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "With 2-set Korean active, type D K S S U D and commit the word 안녕.",
    keyLegends: koreanKeyLegends,
    instructions: koreanInstructions,
  },
  {
    id: "typing-korean-short-phrases",
    language: "korean",
    languageTag: "ko",
    title: "Short phrases",
    mode: "committed",
    target: "안녕 친구",
    expectedText: "안녕 친구",
    sharedPhysicalCodes: [
      "KeyD",
      "KeyK",
      "KeyS",
      "KeyS",
      "KeyU",
      "KeyD",
      "Space",
      "KeyC",
      "KeyL",
      "KeyS",
      "KeyR",
      "KeyN",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "With 2-set Korean active, type D K S S U D, Space, C L S R N, then commit 안녕 친구.",
    keyLegends: koreanKeyLegends,
    instructions: koreanInstructions,
  },
  {
    id: "typing-japanese-basic-hiragana",
    language: "japanese",
    languageTag: "ja",
    title: "Basic hiragana",
    mode: "committed",
    target: "あいうえお",
    expectedText: "あいうえお",
    sharedPhysicalCodes: ["KeyA", "KeyI", "KeyU", "KeyE", "KeyO"],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "With Japanese romaji input active, type A I U E O and commit あいうえお.",
    keyLegends: {},
    instructions: japaneseInstructions,
  },
  {
    id: "typing-japanese-basic-katakana",
    language: "japanese",
    languageTag: "ja",
    title: "Basic katakana",
    mode: "committed",
    target: "カタカナ",
    expectedText: "カタカナ",
    sharedPhysicalCodes: [
      "KeyK",
      "KeyA",
      "KeyT",
      "KeyA",
      "KeyK",
      "KeyA",
      "KeyN",
      "KeyA",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "With Japanese romaji input active, type K A T A K A N A and commit カタカナ.",
    keyLegends: {},
    instructions: japaneseInstructions,
  },
  {
    id: "typing-japanese-standalone-n",
    language: "japanese",
    languageTag: "ja",
    title: "Standalone ん",
    mode: "committed",
    target: "ん",
    expectedText: "ん",
    sharedPhysicalCodes: ["KeyN", "KeyN"],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "Type N N to distinguish standalone ん, then commit it.",
    keyLegends: {},
    instructions: japaneseInstructions,
  },
  {
    id: "typing-japanese-small-tsu",
    language: "japanese",
    languageTag: "ja",
    title: "Small っ",
    mode: "committed",
    target: "きって",
    expectedText: "きって",
    sharedPhysicalCodes: ["KeyK", "KeyI", "KeyT", "KeyT", "KeyE"],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "Type K I T T E. Doubling T produces the small っ in きって.",
    keyLegends: {},
    instructions: japaneseInstructions,
  },
  {
    id: "typing-japanese-long-katakana-vowels",
    language: "japanese",
    languageTag: "ja",
    title: "Long katakana vowels",
    mode: "committed",
    target: "コーヒー",
    expectedText: "コーヒー",
    sharedPhysicalCodes: ["KeyK", "KeyO", "Minus", "KeyH", "KeyI", "Minus"],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "Type K O Hyphen H I Hyphen. The hyphen key produces each long-vowel mark in コーヒー.",
    keyLegends: {},
    instructions: japaneseInstructions,
  },
  {
    id: "typing-japanese-small-kana",
    language: "japanese",
    languageTag: "ja",
    title: "Small kana",
    mode: "committed",
    target: "ゃぁ",
    expectedText: "ゃぁ",
    sharedPhysicalCodes: ["KeyX", "KeyY", "KeyA", "KeyL", "KeyA"],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "Type X Y A for ゃ, then L A for ぁ. Small kana accept either an X or L prefix.",
    keyLegends: {},
    instructions: japaneseInstructions,
  },
  {
    id: "typing-japanese-short-words",
    language: "japanese",
    languageTag: "ja",
    title: "Short words",
    mode: "committed",
    target: "にほんご",
    expectedText: "にほんご",
    sharedPhysicalCodes: [
      "KeyN",
      "KeyI",
      "KeyH",
      "KeyO",
      "KeyN",
      "KeyG",
      "KeyO",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "With Japanese romaji input active, type N I H O N G O and commit にほんご.",
    keyLegends: {},
    instructions: japaneseInstructions,
  },
  {
    id: "typing-japanese-short-phrases",
    language: "japanese",
    languageTag: "ja",
    title: "Short phrases",
    mode: "committed",
    target: "にほんごです",
    expectedText: "にほんごです",
    sharedPhysicalCodes: [
      "KeyN",
      "KeyI",
      "KeyH",
      "KeyO",
      "KeyN",
      "KeyG",
      "KeyO",
      "KeyD",
      "KeyE",
      "KeyS",
      "KeyU",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "With Japanese romaji input active, type N I H O N G O D E S U and commit にほんごです.",
    keyLegends: {},
    instructions: japaneseInstructions,
  },
  {
    id: "typing-french-acute-e",
    language: "french",
    languageTag: "fr",
    title: "Acute é",
    mode: "committed",
    target: "é",
    expectedText: "é",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Quote", "KeyE"],
      macos: ["AltLeft", "KeyE", "KeyE"],
    },
    hint: "Create the acute dead key, then press E and commit é.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-grave-e",
    language: "french",
    languageTag: "fr",
    title: "Grave è",
    mode: "committed",
    target: "è",
    expectedText: "è",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Backquote", "KeyE"],
      macos: ["AltLeft", "Backquote", "KeyE"],
    },
    hint: "Create the grave dead key, then press E and commit è.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-circumflex-e",
    language: "french",
    languageTag: "fr",
    title: "Circumflex ê",
    mode: "committed",
    target: "ê",
    expectedText: "ê",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Digit6", "KeyE"],
      macos: ["AltLeft", "KeyI", "KeyE"],
    },
    hint: "Create the circumflex dead key, then press E and commit ê.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-diaeresis-e",
    language: "french",
    languageTag: "fr",
    title: "Diaeresis ë",
    mode: "committed",
    target: "ë",
    expectedText: "ë",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Quote", "KeyE"],
      macos: ["AltLeft", "KeyU", "KeyE"],
    },
    hint: "Create the diaeresis dead key, then press E and commit ë.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-grave-a",
    language: "french",
    languageTag: "fr",
    title: "Grave à",
    mode: "committed",
    target: "à",
    expectedText: "à",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Backquote", "KeyA"],
      macos: ["AltLeft", "Backquote", "KeyA"],
    },
    hint: "Create the grave dead key, then press A and commit à.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-grave-u",
    language: "french",
    languageTag: "fr",
    title: "Grave ù",
    mode: "committed",
    target: "ù",
    expectedText: "ù",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Backquote", "KeyU"],
      macos: ["AltLeft", "Backquote", "KeyU"],
    },
    hint: "Create the grave dead key, then press U and commit ù.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-circumflex-i",
    language: "french",
    languageTag: "fr",
    title: "Circumflex î",
    mode: "committed",
    target: "î",
    expectedText: "î",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Digit6", "KeyI"],
      macos: ["AltLeft", "KeyI", "KeyI"],
    },
    hint: "Create the circumflex dead key, then press I and commit î.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-circumflex-o",
    language: "french",
    languageTag: "fr",
    title: "Circumflex ô",
    mode: "committed",
    target: "ô",
    expectedText: "ô",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Digit6", "KeyO"],
      macos: ["AltLeft", "KeyI", "KeyO"],
    },
    hint: "Create the circumflex dead key, then press O and commit ô.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-cedilla-c",
    language: "french",
    languageTag: "fr",
    title: "Cedilla ç",
    mode: "committed",
    target: "ç",
    expectedText: "ç",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["AltRight", "Comma"],
      macos: ["AltLeft", "KeyC"],
    },
    hint: "Use the platform shortcut and commit ç.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-ligature-oe",
    language: "french",
    languageTag: "fr",
    title: "Ligature œ",
    mode: "committed",
    target: "œ",
    expectedText: "œ",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: [],
      macos: ["AltLeft", "KeyQ"],
    },
    hint: "On macOS, hold Option and press Q. Otherwise use your configured Unicode input and commit œ.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-left-guillemet",
    language: "french",
    languageTag: "fr",
    title: "Left guillemet «",
    mode: "committed",
    target: "«",
    expectedText: "«",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: [],
      macos: ["AltLeft", "Backslash"],
    },
    hint: "On macOS, hold Option and press Backslash. Otherwise use your configured Unicode input and commit «.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-right-guillemet",
    language: "french",
    languageTag: "fr",
    title: "Right guillemet »",
    mode: "committed",
    target: "»",
    expectedText: "»",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: [],
      macos: ["AltLeft", "ShiftLeft", "Backslash"],
    },
    hint: "On macOS, hold Option and Shift while pressing Backslash. Otherwise use your configured Unicode input and commit ».",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-short-words",
    language: "french",
    languageTag: "fr",
    title: "Short French words",
    mode: "committed",
    target: "déjà hôtel",
    expectedText: "déjà hôtel",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: [
        "KeyD",
        "Quote",
        "KeyE",
        "KeyJ",
        "Backquote",
        "KeyA",
        "Space",
        "KeyH",
        "ShiftLeft",
        "Digit6",
        "KeyO",
        "KeyT",
        "KeyE",
        "KeyL",
      ],
      macos: [
        "KeyD",
        "AltLeft",
        "KeyE",
        "KeyE",
        "KeyJ",
        "AltLeft",
        "Backquote",
        "KeyA",
        "Space",
        "KeyH",
        "AltLeft",
        "KeyI",
        "KeyO",
        "KeyT",
        "KeyE",
        "KeyL",
      ],
    },
    hint: "Type and commit the accented words déjà hôtel.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-french-short-sentence",
    language: "french",
    languageTag: "fr",
    title: "Short French sentence",
    mode: "committed",
    target: "Où est le café ?",
    expectedText: "Où est le café ?",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: [
        "ShiftLeft",
        "KeyO",
        "Backquote",
        "KeyU",
        "Space",
        "KeyE",
        "KeyS",
        "KeyT",
        "Space",
        "KeyL",
        "KeyE",
        "Space",
        "KeyC",
        "KeyA",
        "KeyF",
        "Quote",
        "KeyE",
        "Space",
        "ShiftLeft",
        "Slash",
      ],
      macos: [
        "ShiftLeft",
        "KeyO",
        "AltLeft",
        "Backquote",
        "KeyU",
        "Space",
        "KeyE",
        "KeyS",
        "KeyT",
        "Space",
        "KeyL",
        "KeyE",
        "Space",
        "KeyC",
        "KeyA",
        "KeyF",
        "AltLeft",
        "KeyE",
        "KeyE",
        "Space",
        "ShiftLeft",
        "Slash",
      ],
    },
    hint: "Type and commit the sentence Où est le café ?",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-spanish-tilde-n",
    language: "spanish",
    languageTag: "es",
    title: "Tilde ñ",
    mode: "committed",
    target: "ñ",
    expectedText: "ñ",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Backquote", "KeyN"],
      macos: ["AltLeft", "KeyN", "KeyN"],
    },
    hint: "Create the tilde dead key, then press N and commit ñ.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-spanish-acute-a",
    language: "spanish",
    languageTag: "es",
    title: "Acute á",
    mode: "committed",
    target: "á",
    expectedText: "á",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Quote", "KeyA"],
      macos: ["AltLeft", "KeyE", "KeyA"],
    },
    hint: "Create the acute dead key, then press A and commit á.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-spanish-acute-e",
    language: "spanish",
    languageTag: "es",
    title: "Acute é",
    mode: "committed",
    target: "é",
    expectedText: "é",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Quote", "KeyE"],
      macos: ["AltLeft", "KeyE", "KeyE"],
    },
    hint: "Create the acute dead key, then press E and commit é.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-spanish-acute-i",
    language: "spanish",
    languageTag: "es",
    title: "Acute í",
    mode: "committed",
    target: "í",
    expectedText: "í",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Quote", "KeyI"],
      macos: ["AltLeft", "KeyE", "KeyI"],
    },
    hint: "Create the acute dead key, then press I and commit í.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-spanish-acute-o",
    language: "spanish",
    languageTag: "es",
    title: "Acute ó",
    mode: "committed",
    target: "ó",
    expectedText: "ó",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Quote", "KeyO"],
      macos: ["AltLeft", "KeyE", "KeyO"],
    },
    hint: "Create the acute dead key, then press O and commit ó.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-spanish-acute-u",
    language: "spanish",
    languageTag: "es",
    title: "Acute ú",
    mode: "committed",
    target: "ú",
    expectedText: "ú",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Quote", "KeyU"],
      macos: ["AltLeft", "KeyE", "KeyU"],
    },
    hint: "Create the acute dead key, then press U and commit ú.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-spanish-diaeresis-u",
    language: "spanish",
    languageTag: "es",
    title: "Diaeresis ü",
    mode: "committed",
    target: "ü",
    expectedText: "ü",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Quote", "KeyU"],
      macos: ["AltLeft", "KeyU", "KeyU"],
    },
    hint: "Create the diaeresis dead key, then press U and commit ü.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-spanish-inverted-question",
    language: "spanish",
    languageTag: "es",
    title: "Inverted question mark ¿",
    mode: "committed",
    target: "¿",
    expectedText: "¿",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["AltRight", "Slash"],
      macos: ["AltLeft", "ShiftLeft", "Slash"],
    },
    hint: "Use the platform modifier chord and commit ¿.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-spanish-inverted-exclamation",
    language: "spanish",
    languageTag: "es",
    title: "Inverted exclamation mark ¡",
    mode: "committed",
    target: "¡",
    expectedText: "¡",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["AltRight", "Digit1"],
      macos: ["AltLeft", "Digit1"],
    },
    hint: "Use the platform modifier chord and commit ¡.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-spanish-short-words",
    language: "spanish",
    languageTag: "es",
    title: "Short Spanish words",
    mode: "committed",
    target: "niño pingüino",
    expectedText: "niño pingüino",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: [
        "KeyN",
        "KeyI",
        "ShiftLeft",
        "Backquote",
        "KeyN",
        "KeyO",
        "Space",
        "KeyP",
        "KeyI",
        "KeyN",
        "KeyG",
        "ShiftLeft",
        "Quote",
        "KeyU",
        "KeyI",
        "KeyN",
        "KeyO",
      ],
      macos: [
        "KeyN",
        "KeyI",
        "AltLeft",
        "KeyN",
        "KeyN",
        "KeyO",
        "Space",
        "KeyP",
        "KeyI",
        "KeyN",
        "KeyG",
        "AltLeft",
        "KeyU",
        "KeyU",
        "KeyI",
        "KeyN",
        "KeyO",
      ],
    },
    hint: "Type and commit the words niño pingüino.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-spanish-short-sentence",
    language: "spanish",
    languageTag: "es",
    title: "Short Spanish sentence",
    mode: "committed",
    target: "¿Dónde está? ¡Qué niño más feliz!",
    expectedText: "¿Dónde está? ¡Qué niño más feliz!",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: [
        "AltRight",
        "Slash",
        "ShiftLeft",
        "KeyD",
        "Quote",
        "KeyO",
        "KeyN",
        "KeyD",
        "KeyE",
        "Space",
        "KeyE",
        "KeyS",
        "KeyT",
        "Quote",
        "KeyA",
        "ShiftLeft",
        "Slash",
        "Space",
        "AltRight",
        "Digit1",
        "ShiftLeft",
        "KeyQ",
        "KeyU",
        "Quote",
        "KeyE",
        "Space",
        "KeyN",
        "KeyI",
        "ShiftLeft",
        "Backquote",
        "KeyN",
        "KeyO",
        "Space",
        "KeyM",
        "Quote",
        "KeyA",
        "KeyS",
        "Space",
        "KeyF",
        "KeyE",
        "KeyL",
        "KeyI",
        "KeyZ",
        "ShiftLeft",
        "Digit1",
      ],
      macos: [
        "AltLeft",
        "ShiftLeft",
        "Slash",
        "ShiftLeft",
        "KeyD",
        "AltLeft",
        "KeyE",
        "KeyO",
        "KeyN",
        "KeyD",
        "KeyE",
        "Space",
        "KeyE",
        "KeyS",
        "KeyT",
        "AltLeft",
        "KeyE",
        "KeyA",
        "ShiftLeft",
        "Slash",
        "Space",
        "AltLeft",
        "Digit1",
        "ShiftLeft",
        "KeyQ",
        "KeyU",
        "AltLeft",
        "KeyE",
        "KeyE",
        "Space",
        "KeyN",
        "KeyI",
        "AltLeft",
        "KeyN",
        "KeyN",
        "KeyO",
        "Space",
        "KeyM",
        "AltLeft",
        "KeyE",
        "KeyA",
        "KeyS",
        "Space",
        "KeyF",
        "KeyE",
        "KeyL",
        "KeyI",
        "KeyZ",
        "ShiftLeft",
        "Digit1",
      ],
    },
    hint: "Type and commit the sentence ¿Dónde está? ¡Qué niño más feliz!",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-german-diaeresis-a",
    language: "german",
    languageTag: "de",
    title: "Umlaut ä",
    mode: "committed",
    target: "ä",
    expectedText: "ä",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Quote", "KeyA"],
      macos: ["AltLeft", "KeyU", "KeyA"],
    },
    hint: "Create the umlaut dead key, then press A and commit ä.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-german-diaeresis-o",
    language: "german",
    languageTag: "de",
    title: "Umlaut ö",
    mode: "committed",
    target: "ö",
    expectedText: "ö",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Quote", "KeyO"],
      macos: ["AltLeft", "KeyU", "KeyO"],
    },
    hint: "Create the umlaut dead key, then press O and commit ö.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-german-diaeresis-u",
    language: "german",
    languageTag: "de",
    title: "Umlaut ü",
    mode: "committed",
    target: "ü",
    expectedText: "ü",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Quote", "KeyU"],
      macos: ["AltLeft", "KeyU", "KeyU"],
    },
    hint: "Create the umlaut dead key, then press U and commit ü.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-german-sharp-s",
    language: "german",
    languageTag: "de",
    title: "Sharp s ß",
    mode: "committed",
    target: "ß",
    expectedText: "ß",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["AltRight", "KeyS"],
      macos: ["AltLeft", "KeyS"],
    },
    hint: "Use the platform modifier chord and commit ß.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-german-short-words",
    language: "german",
    languageTag: "de",
    title: "Short German words",
    mode: "committed",
    target: "grüß dich",
    expectedText: "grüß dich",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: [
        "KeyG",
        "KeyR",
        "ShiftLeft",
        "Quote",
        "KeyU",
        "AltRight",
        "KeyS",
        "Space",
        "KeyD",
        "KeyI",
        "KeyC",
        "KeyH",
      ],
      macos: [
        "KeyG",
        "KeyR",
        "AltLeft",
        "KeyU",
        "KeyU",
        "AltLeft",
        "KeyS",
        "Space",
        "KeyD",
        "KeyI",
        "KeyC",
        "KeyH",
      ],
    },
    hint: "Type and commit the German words grüß dich.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-german-short-sentence",
    language: "german",
    languageTag: "de",
    title: "Short German sentence",
    mode: "committed",
    target: "Schöne Grüße aus München.",
    expectedText: "Schöne Grüße aus München.",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: [
        "ShiftLeft",
        "KeyS",
        "KeyC",
        "KeyH",
        "ShiftLeft",
        "Quote",
        "KeyO",
        "KeyN",
        "KeyE",
        "Space",
        "ShiftLeft",
        "KeyG",
        "KeyR",
        "ShiftLeft",
        "Quote",
        "KeyU",
        "AltRight",
        "KeyS",
        "KeyE",
        "Space",
        "KeyA",
        "KeyU",
        "KeyS",
        "Space",
        "ShiftLeft",
        "KeyM",
        "ShiftLeft",
        "Quote",
        "KeyU",
        "KeyN",
        "KeyC",
        "KeyH",
        "KeyE",
        "KeyN",
        "Period",
      ],
      macos: [
        "ShiftLeft",
        "KeyS",
        "KeyC",
        "KeyH",
        "AltLeft",
        "KeyU",
        "KeyO",
        "KeyN",
        "KeyE",
        "Space",
        "ShiftLeft",
        "KeyG",
        "KeyR",
        "AltLeft",
        "KeyU",
        "KeyU",
        "AltLeft",
        "KeyS",
        "KeyE",
        "Space",
        "KeyA",
        "KeyU",
        "KeyS",
        "Space",
        "ShiftLeft",
        "KeyM",
        "AltLeft",
        "KeyU",
        "KeyU",
        "KeyN",
        "KeyC",
        "KeyH",
        "KeyE",
        "KeyN",
        "Period",
      ],
    },
    hint: "Type and commit the sentence Schöne Grüße aus München.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-acute-a",
    language: "portuguese",
    languageTag: "pt",
    title: "Acute á",
    mode: "committed",
    target: "á",
    expectedText: "á",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Quote", "KeyA"],
      macos: ["AltLeft", "KeyE", "KeyA"],
    },
    hint: "Create the acute dead key, then press A and commit á.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-grave-a",
    language: "portuguese",
    languageTag: "pt",
    title: "Grave à",
    mode: "committed",
    target: "à",
    expectedText: "à",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Backquote", "KeyA"],
      macos: ["AltLeft", "Backquote", "KeyA"],
    },
    hint: "Create the grave dead key, then press A and commit à.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-circumflex-a",
    language: "portuguese",
    languageTag: "pt",
    title: "Circumflex â",
    mode: "committed",
    target: "â",
    expectedText: "â",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Digit6", "KeyA"],
      macos: ["AltLeft", "KeyI", "KeyA"],
    },
    hint: "Create the circumflex dead key, then press A and commit â.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-tilde-a",
    language: "portuguese",
    languageTag: "pt",
    title: "Tilde ã",
    mode: "committed",
    target: "ã",
    expectedText: "ã",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Backquote", "KeyA"],
      macos: ["AltLeft", "KeyN", "KeyA"],
    },
    hint: "Create the tilde dead key, then press A and commit ã.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-cedilla-c",
    language: "portuguese",
    languageTag: "pt",
    title: "Cedilla ç",
    mode: "committed",
    target: "ç",
    expectedText: "ç",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["AltRight", "Comma"],
      macos: ["AltLeft", "KeyC"],
    },
    hint: "Use the platform modifier chord and commit ç.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-acute-e",
    language: "portuguese",
    languageTag: "pt",
    title: "Acute é",
    mode: "committed",
    target: "é",
    expectedText: "é",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Quote", "KeyE"],
      macos: ["AltLeft", "KeyE", "KeyE"],
    },
    hint: "Create the acute dead key, then press E and commit é.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-circumflex-e",
    language: "portuguese",
    languageTag: "pt",
    title: "Circumflex ê",
    mode: "committed",
    target: "ê",
    expectedText: "ê",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Digit6", "KeyE"],
      macos: ["AltLeft", "KeyI", "KeyE"],
    },
    hint: "Create the circumflex dead key, then press E and commit ê.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-acute-i",
    language: "portuguese",
    languageTag: "pt",
    title: "Acute í",
    mode: "committed",
    target: "í",
    expectedText: "í",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Quote", "KeyI"],
      macos: ["AltLeft", "KeyE", "KeyI"],
    },
    hint: "Create the acute dead key, then press I and commit í.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-acute-o",
    language: "portuguese",
    languageTag: "pt",
    title: "Acute ó",
    mode: "committed",
    target: "ó",
    expectedText: "ó",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Quote", "KeyO"],
      macos: ["AltLeft", "KeyE", "KeyO"],
    },
    hint: "Create the acute dead key, then press O and commit ó.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-circumflex-o",
    language: "portuguese",
    languageTag: "pt",
    title: "Circumflex ô",
    mode: "committed",
    target: "ô",
    expectedText: "ô",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Digit6", "KeyO"],
      macos: ["AltLeft", "KeyI", "KeyO"],
    },
    hint: "Create the circumflex dead key, then press O and commit ô.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-tilde-o",
    language: "portuguese",
    languageTag: "pt",
    title: "Tilde õ",
    mode: "committed",
    target: "õ",
    expectedText: "õ",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["ShiftLeft", "Backquote", "KeyO"],
      macos: ["AltLeft", "KeyN", "KeyO"],
    },
    hint: "Create the tilde dead key, then press O and commit õ.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-acute-u",
    language: "portuguese",
    languageTag: "pt",
    title: "Acute ú",
    mode: "committed",
    target: "ú",
    expectedText: "ú",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: ["Quote", "KeyU"],
      macos: ["AltLeft", "KeyE", "KeyU"],
    },
    hint: "Create the acute dead key, then press U and commit ú.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-short-words",
    language: "portuguese",
    languageTag: "pt",
    title: "Short Portuguese words",
    mode: "committed",
    target: "ação pão",
    expectedText: "ação pão",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: [
        "KeyA",
        "AltRight",
        "Comma",
        "ShiftLeft",
        "Backquote",
        "KeyA",
        "KeyO",
        "Space",
        "KeyP",
        "ShiftLeft",
        "Backquote",
        "KeyA",
        "KeyO",
      ],
      macos: [
        "KeyA",
        "AltLeft",
        "KeyC",
        "AltLeft",
        "KeyN",
        "KeyA",
        "KeyO",
        "Space",
        "KeyP",
        "AltLeft",
        "KeyN",
        "KeyA",
        "KeyO",
      ],
    },
    hint: "Type and commit the Portuguese words ação pão.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-portuguese-short-sentence",
    language: "portuguese",
    languageTag: "pt",
    title: "Short Portuguese sentence",
    mode: "committed",
    target: "Você está em São Paulo.",
    expectedText: "Você está em São Paulo.",
    sharedPhysicalCodes: [],
    platformPhysicalCodes: {
      windows: [
        "ShiftLeft",
        "KeyV",
        "KeyO",
        "KeyC",
        "ShiftLeft",
        "Digit6",
        "KeyE",
        "Space",
        "KeyE",
        "KeyS",
        "KeyT",
        "Quote",
        "KeyA",
        "Space",
        "KeyE",
        "KeyM",
        "Space",
        "ShiftLeft",
        "KeyS",
        "ShiftLeft",
        "Backquote",
        "KeyA",
        "KeyO",
        "Space",
        "ShiftLeft",
        "KeyP",
        "KeyA",
        "KeyU",
        "KeyL",
        "KeyO",
        "Period",
      ],
      macos: [
        "ShiftLeft",
        "KeyV",
        "KeyO",
        "KeyC",
        "AltLeft",
        "KeyI",
        "KeyE",
        "Space",
        "KeyE",
        "KeyS",
        "KeyT",
        "AltLeft",
        "KeyE",
        "KeyA",
        "Space",
        "KeyE",
        "KeyM",
        "Space",
        "ShiftLeft",
        "KeyS",
        "AltLeft",
        "KeyN",
        "KeyA",
        "KeyO",
        "Space",
        "ShiftLeft",
        "KeyP",
        "KeyA",
        "KeyU",
        "KeyL",
        "KeyO",
        "Period",
      ],
    },
    hint: "Type and commit the sentence Você está em São Paulo.",
    keyLegends: {},
    instructions: deadKeyInstructions,
  },
  {
    id: "typing-russian-top-row",
    language: "russian",
    languageTag: "ru",
    title: "Ё and top row",
    mode: "physical",
    target: "ё й ц у к е н г ш щ з х ъ",
    expectedText: "ёйцукенгшщзхъ",
    sharedPhysicalCodes: [
      "Backquote",
      "KeyQ",
      "KeyW",
      "KeyE",
      "KeyR",
      "KeyT",
      "KeyY",
      "KeyU",
      "KeyI",
      "KeyO",
      "KeyP",
      "BracketLeft",
      "BracketRight",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "Press the Ё and top-row positions in order. No active Russian input source is required.",
    keyLegends: russianKeyLegends,
    instructions: russianInstructions,
  },
  {
    id: "typing-russian-home-row",
    language: "russian",
    languageTag: "ru",
    title: "Home row",
    mode: "physical",
    target: "ф ы в а п р о л д ж э",
    expectedText: "фывапролджэ",
    sharedPhysicalCodes: [
      "KeyA",
      "KeyS",
      "KeyD",
      "KeyF",
      "KeyG",
      "KeyH",
      "KeyJ",
      "KeyK",
      "KeyL",
      "Semicolon",
      "Quote",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "Press the home-row positions in order. No active Russian input source is required.",
    keyLegends: russianKeyLegends,
    instructions: russianInstructions,
  },
  {
    id: "typing-russian-bottom-row",
    language: "russian",
    languageTag: "ru",
    title: "Bottom row",
    mode: "physical",
    target: "я ч с м и т ь б ю",
    expectedText: "ячсмитьбю",
    sharedPhysicalCodes: [
      "KeyZ",
      "KeyX",
      "KeyC",
      "KeyV",
      "KeyB",
      "KeyN",
      "KeyM",
      "Comma",
      "Period",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "Press the bottom-row positions in order. No active Russian input source is required.",
    keyLegends: russianKeyLegends,
    instructions: russianInstructions,
  },
  {
    id: "typing-russian-uppercase-shift",
    language: "russian",
    languageTag: "ru",
    title: "Uppercase with Shift",
    mode: "committed",
    target: "Я",
    expectedText: "Я",
    sharedPhysicalCodes: ["ShiftLeft", "KeyZ"],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "With Russian input active, hold Shift, press Z, and commit Я.",
    keyLegends: russianKeyLegends,
    instructions: russianInstructions,
  },
  {
    id: "typing-russian-short-word",
    language: "russian",
    languageTag: "ru",
    title: "Short Russian word",
    mode: "committed",
    target: "привет",
    expectedText: "привет",
    sharedPhysicalCodes: ["KeyG", "KeyH", "KeyB", "KeyD", "KeyT", "KeyN"],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "With Russian input active, type G H B D T N and commit привет.",
    keyLegends: russianKeyLegends,
    instructions: russianInstructions,
  },
  {
    id: "typing-russian-repeated-letters",
    language: "russian",
    languageTag: "ru",
    title: "Repeated Russian letters",
    mode: "committed",
    target: "русский",
    expectedText: "русский",
    sharedPhysicalCodes: [
      "KeyH",
      "KeyE",
      "KeyC",
      "KeyC",
      "KeyR",
      "KeyB",
      "KeyQ",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "With Russian input active, type H E C C R B Q and commit русский.",
    keyLegends: russianKeyLegends,
    instructions: russianInstructions,
  },
  {
    id: "typing-russian-short-phrase",
    language: "russian",
    languageTag: "ru",
    title: "Short Russian phrase",
    mode: "committed",
    target: "Привет мир",
    expectedText: "Привет мир",
    sharedPhysicalCodes: [
      "ShiftLeft",
      "KeyG",
      "KeyH",
      "KeyB",
      "KeyD",
      "KeyT",
      "KeyN",
      "Space",
      "KeyV",
      "KeyB",
      "KeyH",
    ],
    platformPhysicalCodes: { windows: [], macos: [] },
    hint: "With Russian input active, type the displayed physical sequence and commit Привет мир.",
    keyLegends: russianKeyLegends,
    instructions: russianInstructions,
  },
];

export function detectInstructionPlatform(
  runtimeNavigator: Navigator,
): InstructionPlatform | null {
  const navigatorWithClientHints = runtimeNavigator as Navigator & {
    userAgentData?: { platform?: string };
  };
  const platform =
    navigatorWithClientHints.userAgentData?.platform ||
    runtimeNavigator.platform;
  if (/^mac/i.test(platform)) return "macos";
  if (/^win/i.test(platform)) return "windows";
  return null;
}

export function isInstructionPlatform(
  value: string | null,
): value is InstructionPlatform {
  return value === "windows" || value === "macos";
}
