[package]
name = "meiki-text"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
meiki-domain = { path = "../meiki-domain" }
unicode-general-category.workspace = true
unicode-normalization.workspace = true
unicode-segmentation.workspace = true

[dev-dependencies]
proptest = "1.11"

[lints]
workspace = true
