[package]
name = "meiki-media"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
test-fixtures = []

[dependencies]
hex.workspace = true
infer.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[lints]
workspace = true
